element_index:
    path:     /
    defaults: { _controller: "BackEndBundle:Element:index" }
    methods:  GET

element_show:
    path:     /{id}/show
    defaults: { _controller: "BackEndBundle:Element:show" }
    methods:  GET

element_new:
    path:     /new
    defaults: { _controller: "BackEndBundle:Element:new" }
    methods:  [GET, POST]

element_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackEndBundle:Element:edit" }
    methods:  [GET, POST]

element_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackEndBundle:Element:delete" }
    methods:  DELETE
